
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: quarkus-samples-prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: quarkus-samples-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password  # Standard password: admin

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
      - "12201:12201"  # Åbner TCP-port for GELF
    volumes:
      - ./loki.yaml:/etc/loki/loki-config.yaml
    command: -config.file=/etc/loki/loki-config.yaml


  tempo:
    image: grafana/tempo:latest
    container_name: quarkus-samples-tempo
    ports:
      - "4317:4317"    # OTLP gRPC (traces)
      - "4318:4318"    # OTLP HTTP (traces)
      - "3200:3200"    # Tempo server UI (valgfri)
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml