global:
  scrape_interval: 15s


scrape_configs:
  - job_name: 'quarkus-app'  # Navn på dit scrape job
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['host.docker.internal:8090']  # Hvis Prometheus kører i Docker
